### ISSUE TITLE
Replace css with sass

### ISSUE THREAD

**Issue by codenameyau** [codenameyau/tribble#12]
Now that the project is going through a refactoring, it's a good time to use sass.

**Comment by codenameyau** [comment]
Bleh. Sass is overkill. Invalidating. Posting this here just in case I change my mind.

``` scss
@import '_globals.scss';

body {
  background-color: $gray-f;
  color: $gray-6;
  font-family: $san-serif;
  margin: 0;
}

a {
  color: #4a4a4a;
  text-decoration: none;

  &:hover {
    color: #E75C5C;
  }
}

.container {
  margin: 20px auto;
  text-align: center;
  width: 1280px;
}

.container-header {
  font-size: 24px;
  font-weight: lighter;
  letter-spacing: 5px;
  margin: 40px auto;
  text-transform: uppercase;
}

footer {
  margin: 40px auto;
  text-align: center;
}

.card {
  background: $white;
  box-shadow: 0 0 10px #acacac;
  display: inline-block;
  height: 350px;
  letter-spacing: 1px;
  margin: 20px;
  position: relative;
  vertical-align: top;
  width: 380px;
}

.card-title,
.card-footer {
  font-size: 15px;
  letter-spacing: 2px;
  padding: 20px 0 18px;
  text-transform: uppercase;
  width: 100%;
}

.card-title {
  background: #333333;
  font-size: 15px;
}

.card-footer {
  border-top: 1px solid $gray-c;
  font-size: 12px;
  position: absolute;
  bottom: 0;
  left: 0;
}

.card-title a {
  color: $white;

  &:hover {
    color: #99CCFF;
  }
}

.card-footer a {
  color: $gray-3;

  &:hover {
    color: #E75C5C;
  }
}

.card-body {
  font-size: 16px;
  padding: 20px;
  text-align: left;
}

.card-body-text {
  line-height: 25px;
}
```
